# Generated by Django 2.0 on 2019-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
